start "TestWcfPerformance" "TestWcfPerformance.exe"&
start "TestWcfPerformance" "TestWcfPerformance.exe"&
start "TestWcfPerformance" "TestWcfPerformance.exe"&
start "TestWcfPerformance" "TestWcfPerformance.exe"&
start "TestWcfPerformance" "TestWcfPerformance.exe"&
start "TestWcfPerformance" "TestWcfPerformance.exe"&
start "TestWcfPerformance" "TestWcfPerformance.exe"&
start "TestWcfPerformance" "TestWcfPerformance.exe"&
start "TestWcfPerformance" "TestWcfPerformance.exe"&
start "TestWcfPerformance" "TestWcfPerformance.exe"&
start "TestWcfPerformance" "TestWcfPerformance.exe"&
start "TestWcfPerformance" "TestWcfPerformance.exe"&
start "TestWcfPerformance" "TestWcfPerformance.exe"&
start "TestWcfPerformance" "TestWcfPerformance.exe"&
start "TestWcfPerformance" "TestWcfPerformance.exe"&
start "TestWcfPerformance" "TestWcfPerformance.exe"&
start "TestWcfPerformance" "TestWcfPerformance.exe"&
start "TestWcfPerformance" "TestWcfPerformance.exe"&
start "TestWcfPerformance" "TestWcfPerformance.exe"&
start "TestWcfPerformance" "TestWcfPerformance.exe"&
start "TestWcfPerformance" "TestWcfPerformance.exe"&
start "TestWcfPerformance" "TestWcfPerformance.exe"&
start "TestWcfPerformance" "TestWcfPerformance.exe"&
start "TestWcfPerformance" "TestWcfPerformance.exe"&
start "TestWcfPerformance" "TestWcfPerformance.exe"&
start "TestWcfPerformance" "TestWcfPerformance.exe"&
start "TestWcfPerformance" "TestWcfPerformance.exe"&
start "TestWcfPerformance" "TestWcfPerformance.exe"&
start "TestWcfPerformance" "TestWcfPerformance.exe"&
start "TestWcfPerformance" "TestWcfPerformance.exe"&
start "TestWcfPerformance" "TestWcfPerformance.exe"&
start "TestWcfPerformance" "TestWcfPerformance.exe"&
start "TestWcfPerformance" "TestWcfPerformance.exe"&
start "TestWcfPerformance" "TestWcfPerformance.exe"&
start "TestWcfPerformance" "TestWcfPerformance.exe"&
start "TestWcfPerformance" "TestWcfPerformance.exe"&
start "TestWcfPerformance" "TestWcfPerformance.exe"&
start "TestWcfPerformance" "TestWcfPerformance.exe"&
start "TestWcfPerformance" "TestWcfPerformance.exe"&
start "TestWcfPerformance" "TestWcfPerformance.exe"&
start "TestWcfPerformance" "TestWcfPerformance.exe"&
start "TestWcfPerformance" "TestWcfPerformance.exe"&
start "TestWcfPerformance" "TestWcfPerformance.exe"&
start "TestWcfPerformance" "TestWcfPerformance.exe"&
start "TestWcfPerformance" "TestWcfPerformance.exe"&
start "TestWcfPerformance" "TestWcfPerformance.exe"&
start "TestWcfPerformance" "TestWcfPerformance.exe"&
start "TestWcfPerformance" "TestWcfPerformance.exe"&
start "TestWcfPerformance" "TestWcfPerformance.exe"&
start "TestWcfPerformance" "TestWcfPerformance.exe"&